### ISSUE TITLE
XState plugin shows: Waiting for connection...

### ISSUE THREAD

**Issue by skjorrface** [cpetzel/react-native-flipper-xstate#2]
This is more a question than an issue, maybe I'm doing something wrong, I followed all the instructions, I manage to see the xstate plugin enabled and running, but all it shows while the app is working is the xstate logo and message: Waiting for connection... I'm using flipper 0.122.0. Any hint?

**Comment by cpetzel** [comment]
This means that the inspector is waiting for the mobile app to send events to it. 

What Operating System are you using? (I haven't tested anything other than OSX).

Have you installed the [react native plugin](https://github.com/cpetzel/react-native-flipper-xstate), and recompiled your native apps?  

If it still doesn't work, can you restart Flipper and open up the developer tools (In Menu Bar... View -> Toggle Developer tools), and go to the console tab and copy/paste the entirety of it in here?

**Comment by skjorrface** [comment]
I solved it... it turns out I correctly configured everything but wasn't triggering any transition in my code 😅. Everything works fine now, congratulations for this awesome package!
